import { useMemo, useState } from 'react';
import { useLaboratory } from './provider';
import { selectCurrentUnknown, selectSpecies, selectVisibleInventory } from './selectors';
import type { PhaseDiagramViewModel, SubstanceSummary } from './types';
import { celsiusToKelvin, cubicMetersToLiters, formatPressure, formatTemperature, formatVolume, litersToCubicMeters } from './units';
import './styles.css';

const TABS = ['Composition', 'Products', 'Graphs', 'Phase', 'Timeline', 'Experiment Log'] as const;
type AnalysisTab = typeof TABS[number];
type MobileView = 'Inventory' | 'Lab' | 'Controls' | 'Analysis' | 'Log';
function Metric({ label, value }: { label: string; value: string }) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div>; }

function TopBar() {
  const { snapshot, dispatch } = useLaboratory();
  return <header className="top-bar"><div className="experiment-title"><span className="eyebrow">EXPERIMENT</span><strong>{snapshot.experimentName}</strong></div><div className="top-actions"><button disabled title="Persistence adapter pending">Save</button><button disabled title="Persistence adapter pending">Load</button></div><Metric label="Time" value={`${snapshot.simulationTimeS.toFixed(1)} s`} /><div className={`status-pill ${snapshot.simulationStatus}`}>{snapshot.simulationStatus.toUpperCase()}</div><button onClick={() => dispatch({ type: snapshot.simulationStatus === 'running' ? 'PauseSimulation' : 'Run', vesselId: snapshot.vesselId })}>{snapshot.simulationStatus === 'running' ? 'Pause' : 'Run'}</button><div className="speed-row">{[0.5, 1, 2, 4].map((speed) => <button key={speed} className={snapshot.simulationSpeed === speed ? 'active' : ''} onClick={() => dispatch({ type: 'SetSimulationSpeed', vesselId: snapshot.vesselId, speed })}>×{speed}</button>)}</div><label className="dev-toggle"><input type="checkbox" checked={snapshot.developerMode} onChange={(e) => dispatch({ type: 'SetDeveloperMode', enabled: e.target.checked })}/> Dev</label><button title="Settings scaffold">Settings</button></header>;
}

function InventoryPanel({ selectedId, onSelect }: { selectedId?: string; onSelect: (id: string) => void }) {
  const lab = useLaboratory(); const [query, setQuery] = useState(''); const [amount, setAmount] = useState(0.25);
  const visible = selectVisibleInventory(lab); const filtered = visible.filter((s) => `${s.name} ${s.formula}`.toLowerCase().includes(query.toLowerCase())); const selected = selectSpecies(visible, selectedId) ?? visible[0];
  return <aside className="panel inventory-panel"><div className="panel-heading"><div><span className="eyebrow">UNLOCKED INVENTORY</span><h2>Materials</h2></div><span className="stock">Unlimited stock</span></div><input aria-label="Search substances" className="search" placeholder="Search unlocked materials…" value={query} onChange={(e) => setQuery(e.target.value)} /><div className="inventory-tools"><button className="chip active">All</button><button className="chip">★ Favorites</button><span>{visible.length} available</span></div><div className="substance-list">{filtered.map((s) => <div key={s.speciesId} className={`substance-card ${selected?.speciesId === s.speciesId ? 'selected' : ''}`}><button className="substance-main" onClick={() => onSelect(s.speciesId)}><span className="formula">{s.formula}</span><span><strong>{s.name}</strong><small>Unlocked · unlimited</small></span></button><button aria-label={`Favorite ${s.name}`} className="star" onClick={() => lab.dispatch({ type: 'ToggleFavorite', speciesId: s.speciesId })}>{lab.snapshot.favoriteSpeciesIds.includes(s.speciesId) ? '★' : '☆'}</button></div>)}</div>{selected && <div className="add-box"><div className="amount-header"><span>Amount to add</span><strong>{amount.toFixed(3)} mol</strong></div><input aria-label="Amount" type="number" min="0.001" step="0.01" value={amount} onChange={(e) => setAmount(Number(e.target.value))}/><div className="presets">{[0.01,0.1,0.5,1].map((v) => <button key={v} onClick={() => setAmount(v)}>{v} mol</button>)}</div><button className="primary" disabled={!Number.isFinite(amount) || amount <= 0} onClick={() => lab.dispatch({ type: 'AddSubstance', vesselId: lab.snapshot.vesselId, speciesId: selected.speciesId, amountMol: amount })}>Add {selected.formula} to vessel</button></div>}</aside>;
}

function MoleculeGraphView({ substance }: { substance?: SubstanceSummary }) { return <div className="molecule-view"><div className="molecule-placeholder">{substance?.formula ?? '?'}</div><div><strong>{substance?.name ?? 'Unknown observation'}</strong><p>{substance?.graph ? 'MolecularGraph view model connected.' : '2D structure adapter ready; authoritative graph/layout pending 01 integration.'}</p></div></div>; }

function VesselWorkspace({ selected }: { selected?: SubstanceSummary }) {
  const lab = useLaboratory(); const { snapshot } = lab; const unknown = selectCurrentUnknown(lab); const phases = new Set(snapshot.contents.map((item) => item.phase)); const phaseClass = phases.size > 1 ? 'multiphase' : phases.values().next().value ?? 'empty';
  return <main className="panel vessel-workspace"><div className="panel-heading"><div><span className="eyebrow">REACTION VESSEL</span><h2>Primary vessel</h2></div><span>{formatVolume(snapshot.volumeM3)} / {formatVolume(snapshot.capacityM3)}</span></div><div className="vessel-stage"><div className={`vessel phase-${phaseClass} ${snapshot.simulationStatus === 'running' ? 'active' : ''}`}><div className="gas-headspace">GAS / HEADSPACE</div><div className="liquid-fill"/><div className="solid-deposit"/><div className="vessel-label">{snapshot.contents.length ? `${snapshot.contents.length} entries` : 'Empty'}</div></div><div className="vessel-summary"><Metric label="Temperature" value={formatTemperature(snapshot.temperatureK)} /><Metric label="Pressure" value={formatPressure(snapshot.pressurePa)} /><Metric label="Volume" value={formatVolume(snapshot.volumeM3)} /><span className="eyebrow">CURRENT CONTENTS</span>{snapshot.contents.length ? snapshot.contents.map((item, index) => <div className="composition-chip" key={`${item.speciesId ?? 'unknown'}-${index}`}><strong>{item.identityConfirmed ? item.displayIdentity : 'Unknown'}</strong><span>{item.amountMol.toFixed(3)} mol · phase: {item.phase}</span></div>) : <p className="muted">No material in vessel.</p>}</div></div><div className="inspect-row"><MoleculeGraphView substance={selected}/>{unknown && <div className="unknown-card"><span className="eyebrow">OBSERVATION</span><strong>{unknown.label}</strong><p>Identity remains hidden until a valid analysis result confirms it.</p><button className="primary" onClick={() => lab.dispatch({ type: 'AnalyzeUnknown', observationId: unknown.observationId })}>Analyze</button></div>}</div></main>;
}

function EnvironmentPanel() {
  const { snapshot, dispatch } = useLaboratory(); const [targetC, setTargetC] = useState(snapshot.controls.thermostatTargetK - 273.15);
  const volumeL = cubicMetersToLiters(snapshot.controls.requestedVolumeM3);
  return <aside className="panel environment-panel"><div className="panel-heading"><div><span className="eyebrow">LAB CONTROLS</span><h2>Environment</h2></div></div><section className="control-group"><h3>Thermal</h3><label>Heater power <span>{snapshot.controls.heaterPowerW.toFixed(0)} W</span></label><input aria-label="Heater power" type="range" min="0" max="1000" step="25" value={snapshot.controls.heaterPowerW} onChange={(e) => dispatch({ type: 'SetHeaterPower', vesselId: snapshot.vesselId, powerW: Number(e.target.value) })}/><label>Cooler power <span>{snapshot.controls.coolerPowerW.toFixed(0)} W</span></label><input aria-label="Cooler power" type="range" min="0" max="1000" step="25" value={snapshot.controls.coolerPowerW} onChange={(e) => dispatch({ type: 'SetCoolerPower', vesselId: snapshot.vesselId, powerW: Number(e.target.value) })}/><div className="thermostat"><label><span>Thermostat</span><input aria-label="Thermostat" type="checkbox" checked={snapshot.controls.thermostatEnabled} onChange={(e) => dispatch({ type: 'SetThermostat', vesselId: snapshot.vesselId, enabled: e.target.checked, targetTemperatureK: celsiusToKelvin(targetC) })}/></label><label>Target °C<input aria-label="Thermostat target" type="number" value={targetC} onChange={(e) => setTargetC(Number(e.target.value))} onBlur={() => Number.isFinite(targetC) && dispatch({ type: 'SetThermostat', vesselId: snapshot.vesselId, enabled: snapshot.controls.thermostatEnabled, targetTemperatureK: celsiusToKelvin(targetC) })}/></label></div><p className="hint">Power/controller requests only. Temperature is never overwritten by React.</p></section><section className="control-group"><h3>Vessel / mechanical</h3><label>Volume <span>{volumeL.toFixed(2)} L</span></label><input aria-label="Volume" type="range" min="0.1" max={cubicMetersToLiters(snapshot.capacityM3)} step="0.1" value={volumeL} onChange={(e) => dispatch({ type: 'ChangeVolume', vesselId: snapshot.vesselId, targetVolumeM3: litersToCubicMeters(Number(e.target.value)) })}/><div className="instrument-readout"><span>Pressure</span><strong>{formatPressure(snapshot.pressurePa)}</strong></div><p className="hint">Pressure control remains capability-gated by Game Layer.</p></section><section className="future-slots"><div>Mixing <span>Future</span></div><div>Electrodes <span>Future</span></div><div>Catalyst <span>Future</span></div></section><button className="ghost reset" onClick={() => dispatch({ type: 'ResetExperiment', vesselId: snapshot.vesselId })}>Reset experiment</button></aside>;
}

function PhaseDiagram({ data }: { data?: PhaseDiagramViewModel }) {
  if (!data) return <div className="unavailable"><strong>Phase diagram unavailable</strong><p>No 02/03 phase-boundary dataset is connected for this species.</p></div>;
  const [t0,t1]=data.temperatureRangeK; const [p0,p1]=data.pressureRangePa; const x=(t:number)=>((t-t0)/(t1-t0))*100; const y=(p:number)=>100-((p-p0)/(p1-p0))*100;
  return <div className="phase-card"><div className="phase-head"><strong>Temperature–Pressure phase diagram</strong><span className={`badge ${data.status.toLowerCase()}`}>{data.status}</span></div>{data.fixtureLabel && <p className="fixture-warning">{data.fixtureLabel}</p>}<svg viewBox="0 0 100 100" role="img" aria-label="Phase diagram"><rect x="0" y="0" width="100" height="100" className="phase-bg"/><text x="6" y="15">Solid</text><text x="48" y="32">Liquid</text><text x="70" y="82">Gas</text>{data.boundaries.map((b) => <polyline key={b.id} points={b.samples.map((s) => `${x(s.temperatureK)},${y(s.pressurePa)}`).join(' ')} className="phase-line"/>)}{data.triplePoint && <circle cx={x(data.triplePoint.temperatureK)} cy={y(data.triplePoint.pressurePa)} r="2" className="triple"/>}{data.criticalPoint && <circle cx={x(data.criticalPoint.temperatureK)} cy={y(data.criticalPoint.pressurePa)} r="2" className="critical"/>}{data.currentState && <circle cx={x(data.currentState.temperatureK)} cy={y(data.currentState.pressurePa)} r="2.5" className="current-point"/>}</svg><div className="axis-labels"><span>Temperature →</span><span>Pressure ↑</span></div></div>;
}

function EncyclopediaPanel({ selected }: { selected?: SubstanceSummary }) { const { snapshot, phaseDiagrams } = useLaboratory(); if (!selected) return <div className="unavailable">Select an unlocked species.</div>; const entry = snapshot.encyclopedia.find((e) => e.speciesId === selected.speciesId); return <div className="encyclopedia-card"><MoleculeGraphView substance={selected}/><dl><dt>Scientific status</dt><dd>{selected.scientificStatus}</dd><dt>First discovery</dt><dd>{entry?.firstDiscoveryLabel ?? 'Starter / not recorded'}</dd><dt>Phase info</dt><dd>{entry?.phaseInfo ?? 'Awaiting authoritative data'}</dd><dt>Known properties</dt><dd>{entry?.knownProperties.join(', ') || 'None connected yet'}</dd><dt>Phase diagram</dt><dd>{phaseDiagrams[selected.speciesId] ? 'Available fixture/data' : 'Unavailable'}</dd></dl></div>; }

function AnalysisWorkspace({ selected }: { selected?: SubstanceSummary }) { const lab = useLaboratory(); const [tab,setTab]=useState<AnalysisTab>('Composition'); const diagram=selected ? lab.phaseDiagrams[selected.speciesId] : undefined; return <section className="analysis panel"><nav className="analysis-tabs">{TABS.map((name)=><button key={name} className={tab===name?'active':''} onClick={()=>setTab(name)}>{name}</button>)}</nav><div className="analysis-content">{tab==='Composition' && <table><thead><tr><th>Identity</th><th>Phase</th><th>Amount</th></tr></thead><tbody>{lab.snapshot.contents.length ? lab.snapshot.contents.map((c,i)=><tr key={i}><td>{c.identityConfirmed?c.displayIdentity:'Unknown'}</td><td>{c.phase}</td><td>{c.amountMol.toFixed(3)} mol</td></tr>):<tr><td colSpan={3}>No vessel contents.</td></tr>}</tbody></table>}{tab==='Products' && <div><h3>Products / Analyzer</h3><p>Named products appear only after authoritative observation/analysis confirmation.</p><EncyclopediaPanel selected={selected}/></div>}{tab==='Graphs' && <div className="graph-placeholder">Time-series adapter placeholder: species, T, P, concentration, reaction activity, heater/cooler power.</div>}{tab==='Phase' && <PhaseDiagram data={diagram}/>} {tab==='Timeline' && <div className="timeline">{lab.events.length?lab.events.map((e)=><div className="timeline-row" key={e.id}><span>{e.simulationTimeS.toFixed(1)}s</span><p>{e.message}</p></div>):<p>No events yet.</p>}</div>}{tab==='Experiment Log' && <div className="analysis-card"><strong>{lab.events.length} recorded mock events</strong><p>Save/replay production adapter pending 04/07 integration.</p></div>}</div></section>; }

export function LaboratoryWorkspace() { const lab=useLaboratory(); const visible=selectVisibleInventory(lab); const [selectedId,setSelectedId]=useState<string>(); const selected=useMemo(()=>selectSpecies(visible, selectedId) ?? visible[0],[visible,selectedId]); const [mobileView,setMobileView]=useState<MobileView>('Lab'); return <div className="app-shell"><TopBar/><nav className="mobile-nav">{(['Inventory','Lab','Controls','Analysis','Log'] as MobileView[]).map((v)=><button key={v} className={mobileView===v?'active':''} onClick={()=>setMobileView(v)}>{v}</button>)}</nav><div className={`workspace-grid mobile-${mobileView.toLowerCase()}`}><InventoryPanel selectedId={selected?.speciesId} onSelect={setSelectedId}/><VesselWorkspace selected={selected}/><EnvironmentPanel/></div><AnalysisWorkspace selected={selected}/></div>; }
