import { describe, expect, it } from "vitest";
import { aggregateSystemMatterInventory, createMatterCompartment, transferMatterBatch, type MatterSystemState } from "../../src/simulation/compartment";
import { evaluateGasTransport, evaluateIdealGasCompartment, type GasConnectionTransportModel } from "../../src/simulation/gas-transport";
import { createMoleculeRecord, type ElementDefinition, type ElementProvider, type SpeciesState } from "../../src/simulation/molecular";

const T=300, V=.01;
const N:ElementDefinition={atomicNumber:7,symbol:"N",atomicMolarMassKgPerMol:.014,valenceElectrons:5,commonOxidationStates:[-3,3,5],electronegativity:3.04,typicalValences:[3]};
const provider:ElementProvider={getElement:s=>s==="N"?N:undefined};
const mol=createMoleculeRecord({atoms:[{id:"a",element:"N",formalCharge:0},{id:"b",element:"N",formalCharge:0}],bonds:[{id:"x",a:"a",b:"b",kind:"covalent",order:3}]},provider);
const phase={phase:"gas" as const,source:"06b-longrun",phaseStateId:"gas:06b-longrun",scientificStatus:"APPROXIMATED" as const};
const gas=(id:string,n:number):SpeciesState=>({id,amountMol:n,molecule:mol,phaseState:phase});
const c=(id:string,species:SpeciesState[],kind:"VESSEL_HEADSPACE"|"LAB_ATMOSPHERE"|"GAS_COLLECTOR"="GAS_COLLECTOR",volumeM3=V)=>createMatterCompartment({id,kind,species,volumeM3});
const model=(connectionId:string,g=1e-7):GasConnectionTransportModel=>({connectionId,bulkMolarConductanceMolPerSPaS:g,diffusiveMolarConductanceMolPerSPaS:g,scientificStatus:"APPROXIMATED",source:"06b"});
const thermo=(ids:string[])=>ids.map(compartmentId=>({compartmentId,temperatureK:T}));
function commit(s:MatterSystemState){const e=evaluateGasTransport({system:s,thermodynamicInputs:thermo(s.compartments.map(x=>x.id)),connectionModels:(s.connections??[]).map(x=>model(x.id)),dtS:.1});if(!e.transferRequests.length)return s;const r=transferMatterBatch(s,e.transferRequests);expect(r.status).toBe("COMMITTED");if(r.status!=="COMMITTED")throw new Error("commit");return r.state;}
function pressure(s:MatterSystemState,id:string){return evaluateIdealGasCompartment(s.compartments.find(x=>x.id===id)!,{compartmentId:id,temperatureK:T}).pressurePa??0;}
function totals(s:MatterSystemState){return aggregateSystemMatterInventory(s);}
function expectSame(a:ReturnType<typeof totals>,b:ReturnType<typeof totals>){for(const k of new Set([...Object.keys(a.speciesAmountsMol),...Object.keys(b.speciesAmountsMol)]))expect(a.speciesAmountsMol[k]??0).toBeCloseTo(b.speciesAmountsMol[k]??0,10);for(const k of new Set([...Object.keys(a.elementsMol),...Object.keys(b.elementsMol)]))expect(a.elementsMol[k]??0).toBeCloseTo(b.elementsMol[k]??0,10);expect(a.atomAmountMol).toBeCloseTo(b.atomAmountMol,10);expect(a.netChargeAmountMol).toBeCloseTo(b.netChargeAmountMol,10);}

describe("06B long-run and scaling validation",()=>{
  it("1000-step sealed two-chamber run converges without crossing or drift",()=>{let s:MatterSystemState={compartments:[c("A",[gas("N2",1)],"VESSEL_HEADSPACE"),c("B",[gas("N2",.1)])],connections:[{id:"A-B",sourceCompartmentId:"A",destinationCompartmentId:"B",kind:"GAS",enabled:true}]};const before=totals(s);let d=pressure(s,"A")-pressure(s,"B");for(let i=0;i<1000;i++){s=commit(s);const nd=pressure(s,"A")-pressure(s,"B");expect(Number.isFinite(nd)).toBe(true);expect(nd).toBeGreaterThanOrEqual(-1e-7);expect(nd).toBeLessThanOrEqual(d+1e-7);d=nd;}expectSame(totals(s),before);});

  it("500-step explicit open-headspace route conserves globally and disabled route stops immediately",()=>{let s:MatterSystemState={compartments:[c("head",[gas("N2",1)],"VESSEL_HEADSPACE"),c("lab",[gas("N2",.001)],"LAB_ATMOSPHERE",1)],connections:[{id:"vent",sourceCompartmentId:"head",destinationCompartmentId:"lab",kind:"GAS",enabled:true}]};const before=totals(s);for(let i=0;i<500;i++)s=commit(s);expectSame(totals(s),before);const disabled:{compartments:MatterSystemState["compartments"],connections:NonNullable<MatterSystemState["connections"]>}={compartments:s.compartments,connections:[{...s.connections![0]!,enabled:false}]};const e=evaluateGasTransport({system:disabled,thermodynamicInputs:thermo(["head","lab"]),connectionModels:[model("vent",1)],dtS:1e9});expect(e.transferRequests).toEqual([]);});

  it("small repeated dt agrees with one closed-form step for a two-chamber linear case",()=>{const initial:MatterSystemState={compartments:[c("A",[gas("N2",1)]),c("B",[gas("N2",.1)])],connections:[{id:"A-B",sourceCompartmentId:"A",destinationCompartmentId:"B",kind:"GAS",enabled:true}]};const run=(s:MatterSystemState,dtS:number)=>{const e=evaluateGasTransport({system:s,thermodynamicInputs:thermo(["A","B"]),connectionModels:[model("A-B",1e-8)],dtS});if(!e.transferRequests.length)return s;const r=transferMatterBatch(s,e.transferRequests);if(r.status!=="COMMITTED")throw new Error("commit");return r.state;};let many=initial;for(let i=0;i<100;i++)many=run(many,.01);const once=run(initial,1);expect(pressure(many,"A")).toBeCloseTo(pressure(once,"A"),8);expect(pressure(many,"B")).toBeCloseTo(pressure(once,"B"),8);});

  it("synthetic active-connection/species scaling stays finite and records observations without a fabricated threshold",()=>{const species=Array.from({length:12},(_,i)=>gas(`S${i}`,1/(i+2)));const compartments=[c("S",species,"VESSEL_HEADSPACE"),...Array.from({length:120},(_,i)=>c(`D${i}`,[]))];const connections=Array.from({length:120},(_,i)=>({id:`C${i}`,sourceCompartmentId:"S",destinationCompartmentId:`D${i}`,kind:"GAS" as const,enabled:true}));const input={system:{compartments,connections} satisfies MatterSystemState,thermodynamicInputs:thermo(compartments.map(x=>x.id)),connectionModels:connections.map(x=>model(x.id,1e-9)),dtS:.1};const start=performance.now();const e=evaluateGasTransport(input);const elapsedMs=performance.now()-start;console.log(`06B_PERF activeConnections=${connections.length} relevantSpecies=${species.length} elapsedMs=${elapsedMs.toFixed(3)}`);expect(Number.isFinite(elapsedMs)).toBe(true);expect(e.transferRequests.flatMap(r=>r.species).every(x=>Number.isFinite(x.amountMol)&&x.amountMol>0)).toBe(true);});
});
