import { describe, expect, it } from "vitest";
import { aggregateSystemMatterInventory, createMatterCompartment, transferMatterBatch, type MatterSystemState } from "../../src/simulation/compartment";
import { evaluateGasTransport, evaluateIdealGasCompartment, type GasConnectionTransportModel } from "../../src/simulation/gas-transport";
import { createMoleculeRecord, type ElementDefinition, type ElementProvider, type SpeciesState } from "../../src/simulation/molecular";
import { createDynamicSpeciesRegistry } from "../../src/simulation/species-registry";

const T=300, V=0.01;
const N:ElementDefinition={atomicNumber:7,symbol:"N",atomicMolarMassKgPerMol:.014,valenceElectrons:5,commonOxidationStates:[-3,3,5],electronegativity:3.04,typicalValences:[3]};
const O:ElementDefinition={atomicNumber:8,symbol:"O",atomicMolarMassKgPerMol:.016,valenceElectrons:6,commonOxidationStates:[-2],electronegativity:3.44,typicalValences:[2]};
const H:ElementDefinition={atomicNumber:1,symbol:"H",atomicMolarMassKgPerMol:.001,valenceElectrons:1,commonOxidationStates:[-1,1],electronegativity:2.2,typicalValences:[1]};
const elements:ElementProvider={getElement:s=>({N,O,H} as Record<string,ElementDefinition>)[s]};
const n2=createMoleculeRecord({atoms:[{id:"n1",element:"N",formalCharge:0},{id:"n2",element:"N",formalCharge:0}],bonds:[{id:"nn",a:"n1",b:"n2",kind:"covalent",order:3}]},elements);
const o2=createMoleculeRecord({atoms:[{id:"o1",element:"O",formalCharge:0},{id:"o2",element:"O",formalCharge:0}],bonds:[{id:"oo",a:"o1",b:"o2",kind:"covalent",order:2}]},elements);
const phase={phase:"gas" as const,source:"06b",phaseStateId:"gas:06b",scientificStatus:"APPROXIMATED" as const};
const gas=(id:string,amountMol:number,molecule=n2):SpeciesState=>({id,amountMol,molecule,phaseState:phase});
const c=(id:string,species:SpeciesState[],kind:"VESSEL_HEADSPACE"|"LAB_ATMOSPHERE"|"GAS_COLLECTOR"="GAS_COLLECTOR",volumeM3=V)=>createMatterCompartment({id,kind,species,volumeM3});
const m=(connectionId:string,bulk=0,diffusion=0):GasConnectionTransportModel=>({connectionId,bulkMolarConductanceMolPerSPaS:bulk,diffusiveMolarConductanceMolPerSPaS:diffusion,scientificStatus:"APPROXIMATED",source:"06b"});
const thermo=(ids:string[])=>ids.map(compartmentId=>({compartmentId,temperatureK:T}));
function commit(s:MatterSystemState,e:ReturnType<typeof evaluateGasTransport>){if(!e.transferRequests.length)return s;const r=transferMatterBatch(s,e.transferRequests);expect(r.status).toBe("COMMITTED");if(r.status!=="COMMITTED")throw new Error("commit");return r.state;}
function invEq(a:ReturnType<typeof aggregateSystemMatterInventory>,b:ReturnType<typeof aggregateSystemMatterInventory>){for(const k of new Set([...Object.keys(a.speciesAmountsMol),...Object.keys(b.speciesAmountsMol)]))expect(a.speciesAmountsMol[k]??0).toBeCloseTo(b.speciesAmountsMol[k]??0,11);for(const k of new Set([...Object.keys(a.elementsMol),...Object.keys(b.elementsMol)]))expect(a.elementsMol[k]??0).toBeCloseTo(b.elementsMol[k]??0,11);expect(a.atomAmountMol).toBeCloseTo(b.atomAmountMol,11);expect(a.netChargeAmountMol).toBeCloseTo(b.netChargeAmountMol,11);}
function rnd(seed:number){let x=seed>>>0;return()=>((x=(1664525*x+1013904223)>>>0)/0x100000000);}

describe("06B independent Phase 4A-2 validation",()=>{
 it("invalid thermodynamics and transport inputs are explicit",()=>{for(const [v,t] of [[0,T],[-1,T],[NaN,T],[Infinity,T],[V,0],[V,-1],[V,NaN],[V,Infinity]]){const e=evaluateIdealGasCompartment({...c("A",[gas("N2",1)]),volumeM3:v},{compartmentId:"A",temperatureK:t});expect(e.model).toBe("OPEN");}const system:MatterSystemState={compartments:[c("A",[gas("N2",1)]),c("B",[])],connections:[{id:"A-B",sourceCompartmentId:"A",destinationCompartmentId:"B",kind:"GAS",enabled:true}]};for(const dtS of [0,-1,NaN,Infinity,-Infinity])expect(()=>evaluateGasTransport({system,thermodynamicInputs:thermo(["A","B"]),connectionModels:[m("A-B",1)],dtS})).toThrow();});
 it("equal pressure composition diffusion is separate from bulk",()=>{const system:MatterSystemState={compartments:[c("A",[gas("N2",.5),gas("O2",.5,o2)]),c("B",[gas("N2",.8),gas("O2",.2,o2)])],connections:[{id:"A-B",sourceCompartmentId:"A",destinationCompartmentId:"B",kind:"GAS",enabled:true},{id:"B-A",sourceCompartmentId:"B",destinationCompartmentId:"A",kind:"GAS",enabled:true}]};const e=evaluateGasTransport({system,thermodynamicInputs:thermo(["A","B"]),connectionModels:[m("A-B",1e-6,1e-6),m("B-A",1e-6,1e-6)],dtS:1});expect(e.bulkTransfers).toEqual([]);expect(e.contributions.some(x=>x.speciesId==="O2"&&x.sourceCompartmentId==="A")).toBe(true);expect(e.contributions.some(x=>x.speciesId==="N2"&&x.sourceCompartmentId==="B")).toBe(true);});
 it("large dt, overdraw and ordering remain safe",()=>{const connections=[{id:"A-B",sourceCompartmentId:"A",destinationCompartmentId:"B",kind:"GAS" as const,enabled:true},{id:"A-C",sourceCompartmentId:"A",destinationCompartmentId:"C",kind:"GAS" as const,enabled:true},{id:"A-D",sourceCompartmentId:"A",destinationCompartmentId:"D",kind:"GAS" as const,enabled:true}];const compartments=[c("A",[gas("N2",1)]),c("B",[]),c("C",[]),c("D",[])];const models=connections.map(x=>m(x.id,1));const a=evaluateGasTransport({system:{compartments,connections},thermodynamicInputs:thermo(["A","B","C","D"]),connectionModels:models,dtS:1e300});const b=evaluateGasTransport({system:{compartments:[...compartments].reverse(),connections:[...connections].reverse()},thermodynamicInputs:thermo(["D","C","B","A"]),connectionModels:[...models].reverse(),dtS:1e300});expect(a.transferRequests.flatMap(r=>r.species).reduce((s,x)=>s+x.amountMol,0)).toBeLessThanOrEqual(1);expect(b.transferRequests).toEqual(a.transferRequests);expect(b.contributions).toEqual(a.contributions);});
 it("Phase 4A-1 commit conserves species/elements/atoms/charge",()=>{const system:MatterSystemState={compartments:[c("A",[gas("N2",1),gas("O2",.2,o2)]),c("B",[])],connections:[{id:"A-B",sourceCompartmentId:"A",destinationCompartmentId:"B",kind:"GAS",enabled:true}]};const before=aggregateSystemMatterInventory(system);invEq(aggregateSystemMatterInventory(commit(system,evaluateGasTransport({system,thermodynamicInputs:thermo(["A","B"]),connectionModels:[m("A-B",1,1)],dtS:1e6}))),before);});
 it("generated SpeciesId survives transport",()=>{const water=createMoleculeRecord({atoms:[{id:"o",element:"O",formalCharge:0},{id:"h1",element:"H",formalCharge:0},{id:"h2",element:"H",formalCharge:0}],bonds:[{id:"oh1",a:"o",b:"h1",kind:"covalent",order:1},{id:"oh2",a:"o",b:"h2",kind:"covalent",order:1}]},elements);const resolved=createDynamicSpeciesRegistry({elements}).resolveOrRegister({molecule:water});expect(resolved.status).toBe("GENERATED");if(resolved.status==="INVALID")return;const system:MatterSystemState={compartments:[c("A",[gas(resolved.speciesId,.1,resolved.record.molecule)]),c("B",[])],connections:[{id:"A-B",sourceCompartmentId:"A",destinationCompartmentId:"B",kind:"GAS",enabled:true}]};const next=commit(system,evaluateGasTransport({system,thermodynamicInputs:thermo(["A","B"]),connectionModels:[m("A-B",1)],dtS:1}));expect(next.compartments.find(x=>x.id==="B")?.species[0]?.id).toBe(resolved.speciesId);});
 it("fixed-seed randomized cases are deterministic, finite, conservative and no-overdraw",()=>{const r=rnd(0x06b4a2);for(let i=0;i<50;i++){const aN=r(),aO=r(),bN=r(),bO=r();const system:MatterSystemState={compartments:[c("A",[gas("N2",aN),gas("O2",aO,o2)]),c("B",[gas("N2",bN),gas("O2",bO,o2)]),c("C",[])],connections:[{id:"A-B",sourceCompartmentId:"A",destinationCompartmentId:"B",kind:"GAS",enabled:true},{id:"A-C",sourceCompartmentId:"A",destinationCompartmentId:"C",kind:"GAS",enabled:true},{id:"B-A",sourceCompartmentId:"B",destinationCompartmentId:"A",kind:"GAS",enabled:true}]};const input={system,thermodynamicInputs:thermo(["A","B","C"]),connectionModels:[m("A-B",r()*1e-4,r()*1e-4),m("A-C",r()*1e-4,r()*1e-4),m("B-A",r()*1e-4,r()*1e-4)],dtS:10**(-6+r()*12)};const x=evaluateGasTransport(input);expect(evaluateGasTransport(input)).toEqual(x);expect(x.transferRequests.flatMap(q=>q.species).every(q=>Number.isFinite(q.amountMol)&&q.amountMol>=0)).toBe(true);expect(x.contributions.filter(q=>q.sourceCompartmentId==="A"&&q.speciesId==="N2").reduce((s,q)=>s+q.amountMol,0)).toBeLessThanOrEqual(aN+1e-12);const before=aggregateSystemMatterInventory(system);invEq(aggregateSystemMatterInventory(commit(system,x)),before);}});
 it("multi-connection diagnostics match final normalized bulk requests",()=>{const connections=[{id:"A-B",sourceCompartmentId:"A",destinationCompartmentId:"B",kind:"GAS" as const,enabled:true},{id:"A-C",sourceCompartmentId:"A",destinationCompartmentId:"C",kind:"GAS" as const,enabled:true},{id:"A-D",sourceCompartmentId:"A",destinationCompartmentId:"D",kind:"GAS" as const,enabled:true}];const system:MatterSystemState={compartments:[c("A",[gas("N2",1)]),c("B",[]),c("C",[]),c("D",[])],connections};const e=evaluateGasTransport({system,thermodynamicInputs:thermo(["A","B","C","D"]),connectionModels:connections.map(x=>m(x.id,1)),dtS:1e9});for(const d of e.diagnostics){const final=e.bulkTransfers.find(q=>q.connectionId===d.connectionId)?.species.reduce((s,x)=>s+x.amountMol,0)??0;expect(d.boundedBulkAmountMol??0).toBeCloseTo(final,12);}});
});
